// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaySphere.Infrastructure.Persistence;

#nullable disable

namespace StaySphere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StaySphereDbContext))]
    [Migration("20260827174159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StaySphere.Domain.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Free Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Air conditioning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Flat-screen TV"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mini bar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coffee machine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Safe"
                        },
                        new
                        {
                            Id = 7,
                            Name = "City view"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bathtub"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lounge access"
                        });
                });

            modelBuilder.Entity("StaySphere.Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalPriceCents");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("RoomId", "Status");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("StaySphere.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomNumber = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoomNumber = "102",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            RoomNumber = "103",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            RoomNumber = "201",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            RoomNumber = "202",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            RoomNumber = "301",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            RoomNumber = "302",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            RoomNumber = "401",
                            RoomTypeId = 4
                        });
                });

            modelBuilder.Entity("StaySphere.Domain.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("PricePerNight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PricePerNightCents");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoomTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A comfortable room with a queen bed, ideal for solo travellers or couples.",
                            ImageUrl = "/images/rooms/standard-queen.svg",
                            MaxGuests = 2,
                            Name = "Standard Queen",
                            PricePerNight = 9900L
                        },
                        new
                        {
                            Id = 2,
                            Description = "A spacious room with a king bed, seating area and city views.",
                            ImageUrl = "/images/rooms/deluxe-king.svg",
                            MaxGuests = 2,
                            Name = "Deluxe King",
                            PricePerNight = 15900L
                        },
                        new
                        {
                            Id = 3,
                            Description = "Two-room suite with a king bed and a separate lounge with a sofa bed.",
                            ImageUrl = "/images/rooms/family-suite.svg",
                            MaxGuests = 4,
                            Name = "Family Suite",
                            PricePerNight = 24900L
                        },
                        new
                        {
                            Id = 4,
                            Description = "Premium corner suite with a king bed, work area, lounge and premium amenities.",
                            ImageUrl = "/images/rooms/executive-suite.svg",
                            MaxGuests = 3,
                            Name = "Executive Suite",
                            PricePerNight = 39900L
                        });
                });

            modelBuilder.Entity("StaySphere.Domain.RoomTypeAmenity", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmenityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomTypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomTypeAmenities", (string)null);

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 4
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 7
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 6
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 8
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 9
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 4
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 6
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 7
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 9
                        },
                        new
                        {
                            RoomTypeId = 4,
                            AmenityId = 10
                        });
                });

            modelBuilder.Entity("StaySphere.Domain.Reservation", b =>
                {
                    b.HasOne("StaySphere.Domain.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("StaySphere.Domain.Common.DateRange", "Stay", b1 =>
                        {
                            b1.Property<int>("ReservationId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckOut");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckIn");

                            b1.HasKey("ReservationId");

                            b1.HasIndex("Start", "End");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Room");

                    b.Navigation("Stay")
                        .IsRequired();
                });

            modelBuilder.Entity("StaySphere.Domain.Room", b =>
                {
                    b.HasOne("StaySphere.Domain.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("StaySphere.Domain.RoomTypeAmenity", b =>
                {
                    b.HasOne("StaySphere.Domain.Amenity", "Amenity")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaySphere.Domain.RoomType", "RoomType")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("StaySphere.Domain.Amenity", b =>
                {
                    b.Navigation("RoomTypeAmenities");
                });

            modelBuilder.Entity("StaySphere.Domain.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("StaySphere.Domain.RoomType", b =>
                {
                    b.Navigation("RoomTypeAmenities");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
